### ISSUE TITLE
请增加halifax和bos在uk银行中

### ISSUE THREAD

**Issue by JamesW99** [iniwex5/tools#1]
抓到了这些域名，不知道准不准。

omtrdc.net
vikingcloud.com
tiqcdn.com
halifax.co.uk
halifax-online.com
dpm.demdex.net
lloydsbankinggroup.tt.omtrdc.net
mboxedge38.tt.omtrdc.net
lloydsbankinggroup.d3.sc.omtrdc.net
bankofscotland.co.uk
mboxedge38.tt.omtrdc.net
lloydsbankinggroup.d3.sc.omtrdc.net
lloydsbankinggroup-col.cjteradata.com
zn2rtgq6h2yqvzry1-lloydsbankinggroup.siteintercept.qualtrics.com
zn6kctlxjebku9qkp-lloydsbankinggroup.siteintercept.qualtrics.com

**Comment by iniwex5** [comment]
我因为还没有这些账户所以也不是很清楚准不准，但这些大多数不是重要的，可能代不代理都没啥事，几个关键的加进去了，其实最后还有个co.uk兜底

**Comment by wyshain** [comment]
感谢，主要是发现halifax app不用uk的域名。
